import type { Metadata } from "next";
import "./globals.css";
import jetBrainsMono from "@/fonts/JetBrainsMono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.variable} ${jetBrainsMono.className} antialiased font-bold bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
